version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      # Persist uploaded files and thumbnails between container restarts
      - ./backend/UploadedVideos:/app/UploadedVideos
    ports:
      - "5000:80"
    environment:
      # Optionally specify ASP.NET settings here
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend